FROM nginx:1.23.2
ADD https://unpkg.com/leaflet@1.9.2/dist/leaflet.js /var/www/html/leaflet/
ADD https://unpkg.com/leaflet@1.9.2/dist/leaflet.css /var/www/html/leaflet/
RUN chmod 644 /var/www/html/leaflet/*
